[package]
name="compile_cli"
version="0.0.1"
edition="2024"

[[bin]]
name="compile_cli"
path="src/main.rs"

[dependencies]
syntax = { path = "../../lib/syntax" }
parser = { path = "../../lib/parser" }
