[package]
name="compile_cli"
version="0.0.1"
edition="2024"

[[bin]]
name="compile_cli"
path="src/main.rs"

[dependencies]
compile = { path="../../lib/compile" } 

clap = { version = "4.5.45", features = ["derive"] }
